'use strict';
const ROLES={wolf:{name:'人狼',symbol:'☾',team:'人狼陣営',text:'ほかに人狼がいるか確認します。中央の札は見られません。'},seer:{name:'占い師',symbol:'✧',team:'村人陣営',text:'ほかの人1人の役職、または中央の2枚を確認できます。'},robber:{name:'怪盗',symbol:'⚿',team:'村人陣営',text:'自分とほかの人1人の役職を交換して、受け取る札を確認します。'},villager:{name:'村人',symbol:'⌂',team:'村人陣営',text:'夜の行動はありません。話し合いで情報を集め、人狼を探しましょう。'}};
const $=s=>document.querySelector(s),app=$('#app');
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let config={names:['プレイヤー1','プレイヤー2','プレイヤー3','プレイヤー4'],counts:{wolf:2,seer:1,robber:1,villager:2},minutes:5};
let game=null,screen='setup',selected=[],mode='',revealed=false,timer=null,remaining=300,running=false,deadline=0;
function phase(text){$('#phase').textContent=text;}
function paint(html){app.innerHTML=html;document.body.dataset.screen=screen;window.scrollTo(0,0);}
function button(text,action,cls=''){return `<button class="${cls}" data-action="${action}">${text}</button>`;}
function progress(){return `<div class="progress" aria-label="${game.i+1}人目、全${game.names.length}人">${game.names.map((_,i)=>`<span class="dot ${i<game.i?'done':''} ${i===game.i?'current':''}"></span>`).join('')}</div>`;}
function setup(){screen='setup';phase('準備');paint(`<div class="setup-heading"><div><span class="eyebrow">一台を回して遊ぶ · 日本の基本ルール</span><h1>今夜、人狼は誰？</h1></div>${button('遊び方','rules','secondary small')}</div><div class="layout setup-grid"><section class="panel"><div class="row"><h2><span class="section-number">01</span> 参加する人</h2><div class="counter">${button('−','minus','secondary small')}<strong>${config.names.length}<small>人</small></strong>${button('＋','plus','secondary small')}</div></div><div class="names">${config.names.map((n,i)=>`<label><span class="seat">${String(i+1).padStart(2,'0')}</span><input aria-label="プレイヤー${i+1}の名前" data-name="${i}" value="${esc(n)}" maxlength="20" autocomplete="off"></label>`).join('')}</div><div class="setup-settings"><label>話し合い<select id="minutes">${[3,5,7,10].map(m=>`<option value="${m}" ${config.minutes===m?'selected':''}>${m}分</option>`).join('')}</select></label><p>3〜8人で遊べます。<br>名前を入れて、輪になって座りましょう。</p></div></section><section class="panel"><div class="row"><h2><span class="section-number">02</span> 今夜の配役</h2><span id="count" class="badge"></span></div><div class="role-list">${Object.entries(ROLES).map(([k,r])=>`<label class="role-row ${k}"><span class="role-emblem" aria-hidden="true">${r.symbol}</span><div><strong>${r.name}</strong><span>${r.team}</span></div><input aria-label="${r.name}の枚数" type="number" inputmode="numeric" min="0" max="${k==='wolf'?2:k==='villager'?8:1}" data-role="${k}" value="${config.counts[k]}"></label>`).join('')}</div><div class="row deck-note"><p>全員に1枚、中央に伏せ札2枚。</p>${button('おすすめ配役','preset','secondary small')}</div></section></div><div class="launch-bar"><div><span class="eyebrow">ひと晩だけの推理</span><p>役職確認 → 話し合い → 秘密投票</p><div id="error" class="error" role="alert"></div></div>${button('札を配って、夜を始める','start')}</div>`);count();$('[data-action="minus"]').disabled=config.names.length===3;$('[data-action="plus"]').disabled=config.names.length===8;}
function count(){const total=Object.values(config.counts).reduce((a,b)=>a+b,0);$('#count').textContent=`${total} / ${config.names.length+2}枚`;$('#count').classList.toggle('invalid',total!==config.names.length+2);}
function preset(){config.counts={wolf:2,seer:1,robber:1,villager:config.names.length-2};setup();}
function shuffle(a){for(let i=a.length-1;i>0;i--){const buf=new Uint32Array(1);let x;const limit=Math.floor(4294967296/(i+1))*(i+1);do{crypto.getRandomValues(buf);x=buf[0];}while(x>=limit);const j=x%(i+1);[a[i],a[j]]=[a[j],a[i]];}return a;}
function start(){const n=config.names.map(x=>x.trim()),c=config.counts;let err='';if(n.some(x=>!x))err='全員の名前を入れてください。';else if(new Set(n).size!==n.length)err='区別できるように、名前を変えてください。';else if(Object.entries(c).some(([k,v])=>!Number.isInteger(v)||v<0||v>(k==='wolf'?2:k==='villager'?8:1)))err='役職の枚数を確認してください。';else if(c.wolf<1)err='人狼を1〜2枚入れてください。';else if(Object.values(c).reduce((a,b)=>a+b,0)!==n.length+2)err=`役職を合計${n.length+2}枚にしてください。`;if(err){$('#error').textContent=err;return;}config.names=n;stopTimer();hideOff();const deck=shuffle(Object.entries(c).flatMap(([k,v])=>Array(v).fill(k)));game={names:[...n],original:deck.slice(0,n.length),final:deck.slice(0,n.length),center:deck.slice(n.length),i:0,stage:'night',rob:null,votes:[],log:[]};remaining=config.minutes*60;handoff();}
function handoff(){screen='handoff';revealed=false;selected=[];mode='';phase(game.stage==='night'?'夜 · 秘密の確認':'昼 · 秘密投票');paint(`<section class="handoff"><div class="card-back" aria-hidden="true"><div class="card-ornament">✦</div><span class="moon-mark">☾</span><span class="card-caption">ひと晩の人狼</span><div class="card-ornament">✦</div></div><div class="handoff-copy"><span class="eyebrow">${game.stage==='vote'?'秘密投票':'役職と夜の行動'} · ${game.i+1} / ${game.names.length}</span><h1>${esc(game.names[game.i])}<small>さんへ渡してください</small></h1><p>本人だけが画面を見られるように、<br>タブレットを手元に持ってください。</p>${progress()}${button('私です。秘密の画面を開く','open','wide')}<span class="privacy-note">役職と投票先は、まだ隠れています。</span></div></section>`);}
function privateShell(content){paint(`<section class="private"><div class="secret-head"><div><span class="eyebrow">本人だけで確認</span><h2>${esc(game.names[game.i])}さん</h2></div>${button('画面を隠す','hide','secondary small')}</div>${content}</section>`);}
function options(indices,center=false){return `<div class="choices">${indices.map(i=>`<button class="choice ${selected.includes((center?'c':'p')+i)?'selected':''}" aria-pressed="${selected.includes((center?'c':'p')+i)}" data-pick="${center?'c':'p'}${i}"><span class="choice-number">${center?['A','B'][i]:String(i+1).padStart(2,'0')}</span><span>${center?'中央の札 '+['A','B'][i]:esc(game.names[i])}</span><span class="choice-check" aria-hidden="true">${selected.includes((center?'c':'p')+i)?'✓':'○'}</span></button>`).join('')}</div>`;}
function other(){return game.names.map((_,i)=>i).filter(i=>i!==game.i);}
function nextButton(){return button(game.i===game.names.length-1?'隠して、全員の話し合いへ':'隠して次の人へ','next','wide');}
function roleCard(role){const r=ROLES[role];return `<div class="role-card ${role}"><span class="eyebrow">夜の始めのあなた</span><span class="large-emblem" aria-hidden="true">${r.symbol}</span><h1>${r.name}</h1><span class="team-label">${r.team}</span><p>交換されると、<br>最後の役職は変わるかもしれません。</p></div>`;}
function open(){screen='private';revealed=false;selected=[];mode='';game.stage==='vote'?vote():night();}
function night(){const role=game.original[game.i],r=ROLES[role];let html=`<div class="private-grid">${roleCard(role)}<section class="panel action-panel"><span class="eyebrow">夜の行動</span><h2>${role==='seer'?'どちらを占いますか？':role==='robber'?'誰と役職を交換しますか？':role==='wolf'?'仲間を確認しましょう':'今夜は、静かに休みます。'}</h2><p>${r.text}</p>`;
if(role==='wolf'){const mates=other().filter(i=>game.original[i]==='wolf');html+=`<div class="reveal"><span>${mates.length?'あなた以外の人狼':'あなた以外の人狼は'}</span><strong>${mates.length?mates.map(i=>esc(game.names[i])+'さん').join('、'):'いません'}</strong><p>夜の始めの情報です。怪盗に交換される可能性があります。</p></div><div class="action-bottom">${nextButton()}</div>`;}
else if(role==='seer'){if(revealed)html+=revealHTML()+`<div class="action-bottom">${nextButton()}</div>`;else{html+=`<div class="actions mode-switch">${button('1人を見る','seer-player',mode==='player'?'':'secondary')}${button('中央の2枚を見る','seer-center',mode==='center'?'':'secondary')}</div>`;if(mode==='player')html+=`<p class="selection-label">確認する人を1人選んでください。</p>${options(other())}`;if(mode==='center')html+=`<div class="center-cards"><div class="mini-back">A</div><div class="mini-back">B</div></div><p class="selection-label">中央の2枚を、両方確認します。</p>`;if(mode)html+=button('占い結果を見る','reveal','wide');html+=button('占わずに終える','skip','secondary small skip');}}
else if(role==='robber'){if(revealed)html+=revealHTML()+`<p class="note">あなたはこの役職になります。交換相手には通知されません。新しい役職の夜の能力は使えません。</p><div class="action-bottom">${nextButton()}</div>`;else html+=`${options(other())}${button('この人と交換して確認する','exchange','wide')}${button('交換せずに終える','skip','secondary small skip')}`;}
else html+=`<div class="quiet-note"><span aria-hidden="true">✦</span><p>誰が何を見たのか。<br>朝になったら、話を聞いてみましょう。</p></div><div class="action-bottom">${nextButton()}</div>`;
privateShell(html+'</section></div>');const confirm=$('[data-action="reveal"], [data-action="exchange"]');if(confirm)confirm.disabled=selected.length!==(role==='seer'&&mode==='center'?2:1);}
function revealHTML(){return `<div class="reveal ${game.original[game.i]==='robber'?'robber-result':''}">${selected.map(t=>`<div class="reveal-item"><span>${t[0]==='c'?'中央の札 '+['A','B'][+t.slice(1)]:esc(game.names[+t.slice(1)])+'さん'}${game.original[game.i]==='robber'?'と交換して、あなたは':''}</span><strong>${ROLES[t[0]==='c'?game.center[+t.slice(1)]:game.original[+t.slice(1)]].name}</strong></div>`).join('')}${game.original[game.i]==='seer'?'<p>占い結果は、交換が行われる前の役職です。</p>':''}</div>`;}
function resolveNight(){game.final=[...game.original];if(game.rob){const[a,b]=game.rob;[game.final[a],game.final[b]]=[game.final[b],game.final[a]];game.log.push(`${game.names[a]}さんが${game.names[b]}さんと交換`);}}
function next(){hideOff();game.i++;if(game.i<game.names.length){handoff();return;}game.i=0;if(game.stage==='night'){resolveNight();discussion();}else results();}
function discussion(){screen='discussion';phase('昼 · 話し合い');paint(`<div class="discussion-grid"><section class="discussion-copy"><span class="eyebrow">全員で画面を見てください</span><h1>夜が明けました。</h1><p>誰を占った？ 誰と交換した？<br>見たこと、聞いたことを持ち寄りましょう。</p><div class="badges">${Object.entries(config.counts).filter(([,v])=>v).map(([k,v])=>`<span class="badge">${ROLES[k].name} × ${v}</span>`).join('')}</div><div class="discussion-hints"><p><strong>役職は変わっているかも</strong><br>占いは最初の札。勝敗は最後の札で決まります。</p><p><strong>人狼がいないと思ったら</strong><br>「投票しない」を選べます。全員が投票しなければ、処刑なしになります。</p></div>${button('遊び方を確認','rules','secondary small')}</section><section class="panel timer-panel"><span class="eyebrow">話し合いの時間</span><div id="clock" class="clock" role="timer"></div><div class="actions">${button('タイマーを始める','timer')}${button('時間を戻す','reset-time','secondary')}</div><p class="note">時間が来ても、自動で投票には進みません。</p>${button('話し合いを終えて、秘密投票へ','begin-vote','wide')}</section></div>`);clock();}
function clock(){if(!$('#clock'))return;$('#clock').textContent=`${Math.floor(remaining/60)}:${String(remaining%60).padStart(2,'0')}`;const b=$('[data-action="timer"]');b.textContent=running?'一時停止':remaining===0?'時間になりました':'タイマーを始める';b.disabled=remaining===0;}
function stopTimer(){clearInterval(timer);timer=null;running=false;}
function toggleTimer(){if(running){remaining=Math.max(0,Math.ceil((deadline-Date.now())/1000));stopTimer();}else{running=true;deadline=Date.now()+remaining*1000;timer=setInterval(()=>{remaining=Math.max(0,Math.ceil((deadline-Date.now())/1000));if(!remaining)stopTimer();clock();},250);}clock();}
function vote(){privateShell(`<div class="vote-grid"><div class="vote-copy"><span class="eyebrow">最後の決断</span><h1>人狼は、誰？</h1><p>1人を選ぶか、投票しないを選びます。<br>投票先は、全員が投票するまで秘密です。</p><div class="vote-sigil" aria-hidden="true">☾</div>${progress()}<p class="note">人狼がいないと思ったら「投票しない」を選べます。</p></div><section class="panel action-panel"><h2>投票する相手</h2>${options(other())}<button class="choice abstain ${selected.includes('none')?'selected':''}" data-pick="none" aria-pressed="${selected.includes('none')}"><span class="choice-number">☾</span><span>投票しない（平和村を願う）</span><span class="choice-check">${selected.includes('none')?'✓':'○'}</span></button><div class="vote-confirm"><p id="vote-target">相手を選んでください。</p>${button('投票を確定して、画面を隠す','cast','wide')}</div></section></div>`);$('[data-action="cast"]').disabled=selected.length!==1;if(selected.length)$('#vote-target').textContent=selected[0]==='none'?'誰にも投票しません。':game.names[+selected[0].slice(1)]+'さんに投票します。';}
function outcome(g){const counts=g.names.map((_,i)=>g.votes.filter(v=>v===i).length),max=Math.max(...counts),exiled=counts.map((v,i)=>v===max&&max>=2?i:-1).filter(i=>i>=0),wolves=g.final.map((r,i)=>r==='wolf'?i:-1).filter(i=>i>=0),village=wolves.length?exiled.some(i=>wolves.includes(i)):exiled.length===0;return{counts,exiled,wolves,village};}
function results(){screen='results';phase('結果発表');const o=outcome(game);paint(`<div class="result-heading"><div><span class="eyebrow">ひと晩の真相</span><h1 class="win">${o.village?'村人陣営の勝ち':o.wolves.length?'人狼陣営の勝ち':'全員の負け'}</h1><p>${o.exiled.length?'処刑：'+o.exiled.map(i=>esc(game.names[i])+'さん').join('、'):'2票以上を集めた人がいないため、処刑なし。'} · ${o.wolves.length?(o.village?'人狼が処刑されました。':'人狼は処刑されませんでした。'):'人狼のいない平和村でした。'}</p></div><div class="actions">${button('もう一度遊ぶ','again')}${button('設定に戻る','setup','secondary')}</div></div><div class="result-grid"><section class="panel"><h2>最後の役職</h2><div class="table-wrap"><table class="result-table"><thead><tr><th>名前</th><th>最初の札</th><th>最後の札</th><th>得票</th></tr></thead><tbody>${game.names.map((n,i)=>`<tr class="${o.exiled.includes(i)?'exiled':''}"><td>${esc(n)}${o.exiled.includes(i)?' <span class="execution">処刑</span>':''}</td><td>${ROLES[game.original[i]].name}</td><td><strong class="${game.final[i]==='wolf'?'wolf-text':''}">${ROLES[game.final[i]].name}</strong></td><td>${o.counts[i]}票</td></tr>`).join('')}</tbody></table></div><p class="note">勝った人：${game.names.filter((_,i)=>o.village?game.final[i]!=='wolf':o.wolves.length&&game.final[i]==='wolf').map(esc).join('、')||'なし'}</p></section><section class="panel result-side"><h3>中央に残っていた札</h3><div class="center-results">${game.center.map((r,i)=>`<div><span>${['A','B'][i]}</span><span class="role-emblem" aria-hidden="true">${ROLES[r].symbol}</span><strong>${ROLES[r].name}</strong></div>`).join('')}</div><h3>怪盗の行動</h3><p class="note">${game.log.length?game.log.map(esc).join('<br>'):'役職の交換はありませんでした。'}</p><details><summary>投票の記録</summary><div class="stack">${game.names.map((n,i)=>`<div class="row"><span>${esc(n)}</span><span class="muted">→ ${game.votes[i]===null?'投票しない':esc(game.names[game.votes[i]])}</span></div>`).join('')}</div></details></section></div>`);}
function rules(){const dialog=$('#rules');dialog.innerHTML=`<div class="rule-modal"><div class="row"><div><span class="eyebrow">日本の基本ルールをベースに</span><h2>ひと晩の遊び方</h2></div><button class="secondary small" id="close-rules" autofocus>閉じる</button></div><div class="rule-sections"><section><h3>01 準備</h3><p>人狼2枚、占い師1枚、怪盗1枚、村人は人数−2枚がおすすめ。全員に1枚配り、中央に2枚を伏せます。人数はこのアプリでは3〜8人です。</p></section><section><h3>02 夜の行動</h3><p>占い師はほかの人1人か中央の2枚を確認。人狼は最初の仲間を確認。怪盗はほかの人1人と交換して受け取る役職を確認。村人は待機します。占いと怪盗の交換は見送れます。</p><p>1台を回すため操作は席順ですが、占いと仲間確認は交換前の札を対象にし、全員の確認後に怪盗の交換を確定します。交換相手には通知しません。交換で手に入れた役職の夜の能力は使えません。</p></section><section class="role-guide"><h3>村人 · 村人陣営</h3><p>夜の特殊能力はありません。占い結果や怪盗の交換、発言の食い違いから人狼を推理します。怪盗に交換されていたら、最後の役職と陣営が変わっていることもあります。</p></section><section class="role-guide"><h3>人狼 · 人狼陣営</h3><p>夜の始めに、ほかの人狼が誰かを確認します。仲間がいない場合も中央の札は見られません。昼は正体を隠し、人狼が誰も処刑されないように立ち回ります。人狼が2人いても、1人が処刑されれば人狼陣営は負けです。怪盗に交換されていれば村人陣営になります。</p></section><section class="role-guide"><h3>占い師 · 村人陣営</h3><p>「自分以外の1人の役職」か「中央の2枚すべて」のどちらかを確認できます。両方は見られません。占いは見送ることもできます。見えるのは怪盗の交換前の役職なので、占った人の最後の役職が同じとは限りません。</p></section><section class="role-guide"><h3>怪盗 · 交換した役職の陣営</h3><p>自分とほかの人1人の札を交換し、受け取った役職を確認します。交換せずに終えてもかまいません。中央の札とは交換できません。人狼を受け取れば人狼陣営、それ以外なら村人陣営になります。交換相手には通知されず、新しい役職の夜の能力は使えません。</p></section><section><h3>03 話し合い</h3><p>自分の役職や確認した情報を話します。どの陣営も嘘をついてかまいません。役職画面を他人に見せて証明するのはやめましょう。夜の襲撃や途中の脱落はありません。</p></section><section><h3>04 秘密投票</h3><p>各自が自分以外の1人に1票、または「投票しない」を選びます。投票しないは誰の得票にも加えません。2票以上の最多得票者を処刑し、同数最多なら全員処刑。全員が投票しない場合や、全員の得票が1票以下の場合は誰も処刑しません。投票しない人がいても、誰かに2票以上集まれば処刑が行われます。</p></section><section><h3>05 勝敗</h3><p>交換後の役職で判定。人狼を1人でも処刑すれば村人陣営の勝ち。人狼がいるのに処刑できなければ人狼陣営の勝ち。人狼が中央にしかいない平和村では、処刑なしなら全員の勝ち、誰かを処刑すると全員の負けです。</p></section><section><h3>安心して回すために</h3><p>必ず隠すボタンを押してから渡してください。別のタブやアプリに移ると秘密の画面を隠します。再読み込みするとゲームはリセットされます。</p></section></div></div>`;dialog.showModal();$('#close-rules').onclick=()=>dialog.close();}
function hide(){if(screen==='private')$('#privacy').hidden=false;}
function hideOff(){$('#privacy').hidden=true;}
$('#resume').onclick=hideOff;
document.addEventListener('visibilitychange',()=>{if(document.hidden)hide();});window.addEventListener('blur',hide);
app.addEventListener('input',e=>{if(e.target.dataset.name!==undefined)config.names[+e.target.dataset.name]=e.target.value;if(e.target.dataset.role){config.counts[e.target.dataset.role]=Number(e.target.value);count();}if(e.target.id==='minutes')config.minutes=+e.target.value;});
app.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||b.disabled)return;const a=b.dataset.action,t=b.dataset.pick;if(t){if(revealed)return;selected=selected.includes(t)?[]:[t];game.stage==='vote'?vote():night();return;}switch(a){case'plus':if(config.names.length<8){let k=config.names.length+1;while(config.names.includes('プレイヤー'+k))k++;config.names.push('プレイヤー'+k);preset();}break;case'minus':if(config.names.length>3){config.names.pop();preset();}break;case'preset':preset();break;case'start':start();break;case'open':open();break;case'hide':hide();break;case'rules':rules();break;case'seer-player':mode='player';selected=[];night();break;case'seer-center':mode='center';selected=['c0','c1'];night();break;case'reveal':revealed=true;night();break;case'exchange':game.rob=[game.i,+selected[0].slice(1)];revealed=true;night();break;case'skip':next();break;case'next':next();break;case'timer':toggleTimer();break;case'reset-time':stopTimer();remaining=config.minutes*60;clock();break;case'begin-vote':stopTimer();game.stage='vote';game.i=0;handoff();break;case'cast':game.votes[game.i]=selected[0]==='none'?null:+selected[0].slice(1);next();break;case'again':start();break;case'setup':stopTimer();game=null;setup();break;}});
setup();
